edition = "2021"
hard_tabs = true
fn_params_layout = "Tall"
force_explicit_abi = true
match_block_trailing_comma = false
max_width = 150
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
use_field_init_shorthand = true
use_small_heuristics = "Default"
# Unstable formatting options below; remove if you REALLY don't wanna use `cargo +nightly fmt`
unstable_features = true
binop_separator = "Front"
brace_style = "SameLineWhere"
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
empty_item_single_line = true
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
group_imports = "Preserve"
imports_granularity = "Crate"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
match_arm_blocks = true
normalize_comments = true
overflow_delimited_expr = true
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Wide"
wrap_comments = true
